//! HUDData 的 Rust 移植 (src/ui/overlay/model/HUDData.java)。
//! 本模块同时是 P2 批二的挂载根: 子模块 `gauge_marker`/`marker_type`
//! (src/ui/component/gauge/, CLASSIFY.md A 类) 经此处 mod 声明挂到 lib.rs
//! 已预挂的 `hud_data` 挂载点。
//!
//! PORT: java.awt.Color 数据字段 → [u8;4] RGBA (POC 先例);
//!      Color.GREEN = (0,255,0,255) (Java 8 oracle 实测, new Color(r,g,b) alpha 固定 255)。
//! PORT: Java Builder 公有可变字段直赋 (`b.ias = ...`) → pub 字段;
//!      Java 字段初始化器的非零默认 (GREEN/"") 由 Default impl 承载,
//!      数值 0/boolean false 显式写出 (§2.10)。
//! PORT: 字段 `speedBar_speedRatio` → `speed_bar_speed_ratio` (camelCase→snake_case,
//!      原名本就含下划线)。

pub mod gauge_marker;
pub mod marker_type;

pub use gauge_marker::GaugeMarker;
pub use marker_type::MarkerType;

/// Immutable value object containing all necessary data for one frame of HUD
/// rendering.
/// Generated by HUDCalculator.
// PORT: Java 未覆写 equals, `==` 是引用同一性; 此处 PartialEq 仅为测试断言设施,
// 消费端翻译 Java `==` 时不得借用值相等 (§2.6, 含 Builder/GaugeMarker 同理)。
#[derive(Debug, Clone, PartialEq)]
pub struct HUDData {
    // Flight Dynamics
    pub ias: f64, // Indicated Airspeed (km/h)
    pub mach: f64, // Mach number
    pub altitude: f64, // Barometric altitude (m)
    pub radio_altitude: f64, // Radio altitude (m)
    pub vertical_speed: f64, // SEP (m/s)
    pub heading: f64, // Heading (degrees, 0-360)
    pub pitch: f64, // Pitch (degrees)
    pub roll: f64, // Roll (degrees)
    pub slip: f64, // Side slip (deg or relative)
    pub aoa: f64, // Angle of Attack
    pub pitch_valid: bool, // True if pitch data available from API

    // System State
    pub throttle: i32, // 0-110%
    pub flaps: f64, // 0-100%
    pub gear: f64, // 0-100%
    pub airbrake: f64, // 0-100%
    pub flap_allow_angle: f64, // Max safe angle based on speed

    // Calculated/Derived Metrics
    pub energy_m: f64, // Energy/Mass
    pub g_load: f64, // Ny
    pub turn_rate: f64, // Degrees/sec
    pub maneuver_index: f64, // 0.0 - 1.0 (Energy Maneuverability)
    pub is_mach_mode: bool,
    pub is_gear_down: bool,
    pub is_flaps_down: bool,
    pub is_airbrake_active: bool,

    // Warnings & Limits
    pub warn_vne: bool, // Velocity Not Exceed
    pub warn_stall: bool, // AoA Limit
    pub warn_gear: bool, // Gear speed warning
    pub warn_altitude: bool, // Ground proximity
    pub aoa_color: [u8; 4], // Color for AoA indicator
    pub aoa_bar_color: [u8; 4], // Color for AoA Bar
    pub throttle_color: [u8; 4], // Color for Throttle
    pub warn_configuration: bool, // Flaps/Gear/Airbrake transition or speed warning

    // Context Info
    pub map_grid: String, // e.g. "C4"
    pub time_str: String, // Mission time or Fuel time

    // Formatting Helpers (Optional, can be computed by components if raw data is
    // sufficient)
    pub speed_str: String,
    pub alt_str: String,
    pub aoa_str: String,
    pub energy_str: String,
    pub mechanization_str: String,
    /// 组件级拆分：襟翼/可变翼文字（如 "F100" / "W 50" / "    "）
    pub flaps_wing_str: String,
    /// 组件级拆分：减速板文字（"BRK" 或 ""）
    pub airbrake_str: String,
    /// 组件级拆分：起落架文字（"GEA" 或 ""）
    pub gear_str: String,
    pub sep_str: String,
    pub maneuver_state_str: String,
    pub aoa_ratio: f64, // Normalized AoA for bar (0.0 - 1.0+)

    // Speed Bar Metrics
    pub speed_bar_speed_ratio: f64,
    pub speed_bar_stall_ratio: f64,
    pub speed_bar_unit_mach_limit_ratio: f64,
    pub speed_bar_aileron_lock_ratio: f64,
    pub speed_bar_rudder_lock_ratio: f64,
}

impl HUDData {
    /// 对应 Java 包私有构造器 `HUDData(Builder builder)`: 按原赋值顺序逐字段拷贝。
    fn from_builder(builder: &Builder) -> Self {
        HUDData {
            ias: builder.ias,
            mach: builder.mach,
            altitude: builder.altitude,
            radio_altitude: builder.radio_altitude,
            vertical_speed: builder.vertical_speed,
            heading: builder.heading,
            pitch: builder.pitch,
            roll: builder.roll,
            slip: builder.slip,
            aoa: builder.aoa,
            pitch_valid: builder.pitch_valid,
            throttle: builder.throttle,
            flaps: builder.flaps,
            gear: builder.gear,
            airbrake: builder.airbrake,
            flap_allow_angle: builder.flap_allow_angle,
            energy_m: builder.energy_m,
            g_load: builder.g_load,
            turn_rate: builder.turn_rate,
            maneuver_index: builder.maneuver_index,
            is_mach_mode: builder.is_mach_mode,
            is_gear_down: builder.is_gear_down,
            is_flaps_down: builder.is_flaps_down,
            is_airbrake_active: builder.is_airbrake_active,
            warn_vne: builder.warn_vne,
            warn_stall: builder.warn_stall,
            warn_gear: builder.warn_gear,
            warn_altitude: builder.warn_altitude,
            aoa_color: builder.aoa_color,
            aoa_bar_color: builder.aoa_bar_color,
            throttle_color: builder.throttle_color,
            map_grid: builder.map_grid.clone(),
            time_str: builder.time_str.clone(),
            speed_str: builder.speed_str.clone(),
            alt_str: builder.alt_str.clone(),
            aoa_str: builder.aoa_str.clone(),
            energy_str: builder.energy_str.clone(),
            mechanization_str: builder.mechanization_str.clone(),
            flaps_wing_str: builder.flaps_wing_str.clone(),
            airbrake_str: builder.airbrake_str.clone(),
            gear_str: builder.gear_str.clone(),
            sep_str: builder.sep_str.clone(),
            maneuver_state_str: builder.maneuver_state_str.clone(),
            aoa_ratio: builder.aoa_ratio,
            warn_configuration: builder.warn_configuration,
            speed_bar_speed_ratio: builder.speed_bar_speed_ratio,
            speed_bar_stall_ratio: builder.speed_bar_stall_ratio,
            speed_bar_unit_mach_limit_ratio: builder.speed_bar_unit_mach_limit_ratio,
            speed_bar_aileron_lock_ratio: builder.speed_bar_aileron_lock_ratio,
            speed_bar_rudder_lock_ratio: builder.speed_bar_rudder_lock_ratio,
        }
    }
}

/// 对应 Java `public static class Builder`: 公有可变字段直赋 + `build()`。
#[derive(Debug, Clone, PartialEq)]
pub struct Builder {
    // Defaults
    pub ias: f64,
    pub mach: f64,
    pub altitude: f64,
    pub radio_altitude: f64,
    pub vertical_speed: f64,
    pub heading: f64,
    pub pitch: f64,
    pub roll: f64,
    pub slip: f64,
    pub aoa: f64,
    pub pitch_valid: bool,
    pub throttle: i32,
    pub flaps: f64,
    pub gear: f64,
    pub airbrake: f64,
    pub flap_allow_angle: f64,
    pub energy_m: f64,
    pub g_load: f64,
    pub turn_rate: f64,
    pub maneuver_index: f64,
    pub is_mach_mode: bool,
    pub is_gear_down: bool,
    pub is_flaps_down: bool,
    pub is_airbrake_active: bool,
    pub warn_vne: bool,
    pub warn_stall: bool,
    pub warn_gear: bool,
    pub warn_altitude: bool,
    pub aoa_color: [u8; 4],
    pub aoa_bar_color: [u8; 4],
    pub throttle_color: [u8; 4],
    pub map_grid: String,
    pub time_str: String,
    pub speed_str: String,
    pub alt_str: String,
    pub aoa_str: String,
    pub energy_str: String,
    pub mechanization_str: String,
    pub flaps_wing_str: String,
    pub airbrake_str: String,
    pub gear_str: String,
    pub sep_str: String,
    pub maneuver_state_str: String,
    pub warn_configuration: bool,
    pub aoa_ratio: f64,

    // Speed Ratio Bar metrics
    pub speed_bar_speed_ratio: f64,
    pub speed_bar_stall_ratio: f64,
    pub speed_bar_unit_mach_limit_ratio: f64,
    pub speed_bar_aileron_lock_ratio: f64,
    pub speed_bar_rudder_lock_ratio: f64,
}

impl Default for Builder {
    /// Java 字段初始化器的默认值 (Java 8 oracle 实测):
    /// 数值 0 / boolean false / Color.GREEN / 空串。
    fn default() -> Self {
        Builder {
            ias: 0.0,
            mach: 0.0,
            altitude: 0.0,
            radio_altitude: 0.0,
            vertical_speed: 0.0,
            heading: 0.0,
            pitch: 0.0,
            roll: 0.0,
            slip: 0.0,
            aoa: 0.0,
            pitch_valid: false,
            throttle: 0,
            flaps: 0.0,
            gear: 0.0,
            airbrake: 0.0,
            flap_allow_angle: 0.0,
            energy_m: 0.0,
            g_load: 0.0,
            turn_rate: 0.0,
            maneuver_index: 0.0,
            is_mach_mode: false,
            is_gear_down: false,
            is_flaps_down: false,
            is_airbrake_active: false,
            warn_vne: false,
            warn_stall: false,
            warn_gear: false,
            warn_altitude: false,
            aoa_color: [0, 255, 0, 255], // Color.GREEN
            aoa_bar_color: [0, 255, 0, 255], // Color.GREEN
            throttle_color: [0, 255, 0, 255], // Color.GREEN
            map_grid: String::new(),
            time_str: String::new(),
            speed_str: String::new(),
            alt_str: String::new(),
            aoa_str: String::new(),
            energy_str: String::new(),
            mechanization_str: String::new(),
            flaps_wing_str: String::new(),
            airbrake_str: String::new(),
            gear_str: String::new(),
            sep_str: String::new(),
            maneuver_state_str: String::new(),
            warn_configuration: false,
            aoa_ratio: 0.0,
            speed_bar_speed_ratio: 0.0,
            speed_bar_stall_ratio: 0.0,
            speed_bar_unit_mach_limit_ratio: 0.0,
            speed_bar_aileron_lock_ratio: 0.0,
            speed_bar_rudder_lock_ratio: 0.0,
        }
    }
}

impl Builder {
    /// 对应 Java `public HUDData build()`: 非消费式, Builder 可重复使用。
    pub fn build(&self) -> HUDData {
        HUDData::from_builder(self)
    }
}

#[cfg(test)]
mod tests {
    // PORT: Java 保真 — 测试构造沿用 Java `new X(); x.f = v;` 逐字段赋值形态,
    // 不改成 struct 字面量以保持与 Java 测试源逐行对应
    #![allow(clippy::field_reassign_with_default)]

    use super::*;

    /// Java 8 oracle: `new HUDData.Builder()` 的全部默认值
    /// (ias=0.0 ... throttle=0, pitchValid=false, 三色 GREEN, 全部空串, sb_rudder=0.0)。
    #[test]
    fn builder_defaults_match_java() {
        let b = Builder::default();
        assert_eq!(b.ias, 0.0);
        assert_eq!(b.mach, 0.0);
        assert_eq!(b.altitude, 0.0);
        assert_eq!(b.radio_altitude, 0.0);
        assert_eq!(b.vertical_speed, 0.0);
        assert_eq!(b.heading, 0.0);
        assert_eq!(b.pitch, 0.0);
        assert_eq!(b.roll, 0.0);
        assert_eq!(b.slip, 0.0);
        assert_eq!(b.aoa, 0.0);
        assert!(!b.pitch_valid);
        assert_eq!(b.throttle, 0);
        assert_eq!(b.flaps, 0.0);
        assert_eq!(b.gear, 0.0);
        assert_eq!(b.airbrake, 0.0);
        assert_eq!(b.flap_allow_angle, 0.0);
        assert_eq!(b.energy_m, 0.0);
        assert_eq!(b.g_load, 0.0);
        assert_eq!(b.turn_rate, 0.0);
        assert_eq!(b.maneuver_index, 0.0);
        assert!(!b.is_mach_mode);
        assert!(!b.is_gear_down);
        assert!(!b.is_flaps_down);
        assert!(!b.is_airbrake_active);
        assert!(!b.warn_vne);
        assert!(!b.warn_stall);
        assert!(!b.warn_gear);
        assert!(!b.warn_altitude);
        assert_eq!(b.aoa_color, [0, 255, 0, 255]);
        assert_eq!(b.aoa_bar_color, [0, 255, 0, 255]);
        assert_eq!(b.throttle_color, [0, 255, 0, 255]);
        assert_eq!(b.map_grid, "");
        assert_eq!(b.time_str, "");
        assert_eq!(b.speed_str, "");
        assert_eq!(b.alt_str, "");
        assert_eq!(b.aoa_str, "");
        assert_eq!(b.energy_str, "");
        assert_eq!(b.mechanization_str, "");
        assert_eq!(b.flaps_wing_str, "");
        assert_eq!(b.airbrake_str, "");
        assert_eq!(b.gear_str, "");
        assert_eq!(b.sep_str, "");
        assert_eq!(b.maneuver_state_str, "");
        assert!(!b.warn_configuration);
        assert_eq!(b.aoa_ratio, 0.0);
        assert_eq!(b.speed_bar_speed_ratio, 0.0);
        assert_eq!(b.speed_bar_stall_ratio, 0.0);
        assert_eq!(b.speed_bar_unit_mach_limit_ratio, 0.0);
        assert_eq!(b.speed_bar_aileron_lock_ratio, 0.0);
        assert_eq!(b.speed_bar_rudder_lock_ratio, 0.0);
    }

    /// build() 逐字段拷贝: 对全部字段设置非默认哨兵值后核对。
    #[test]
    fn build_copies_all_fields() {
        let mut b = Builder::default();
        b.ias = 412.5;
        b.mach = 0.82;
        b.altitude = 5300.0;
        b.radio_altitude = 245.7;
        b.vertical_speed = -13.2;
        b.heading = 359.9;
        b.pitch = -12.25;
        b.roll = 60.0;
        b.slip = 0.5;
        b.aoa = 18.3;
        b.pitch_valid = true;
        b.throttle = 110;
        b.flaps = 100.0;
        b.gear = 55.0;
        b.airbrake = 20.0;
        b.flap_allow_angle = 25.0;
        b.energy_m = 1520.4;
        b.g_load = 7.5;
        b.turn_rate = 22.4;
        b.maneuver_index = 0.97;
        b.is_mach_mode = true;
        b.is_gear_down = true;
        b.is_flaps_down = true;
        b.is_airbrake_active = true;
        b.warn_vne = true;
        b.warn_stall = true;
        b.warn_gear = true;
        b.warn_altitude = true;
        b.aoa_color = [255, 64, 64, 255];
        b.aoa_bar_color = [255, 192, 0, 128];
        b.throttle_color = [64, 255, 128, 200];
        b.map_grid = "C4".to_string();
        b.time_str = "12:34".to_string();
        b.speed_str = "413".to_string();
        b.alt_str = "5300".to_string();
        b.aoa_str = "18.3".to_string();
        b.energy_str = "1520".to_string();
        b.mechanization_str = "F100".to_string();
        b.flaps_wing_str = "W 50".to_string();
        b.airbrake_str = "BRK".to_string();
        b.gear_str = "GEA".to_string();
        b.sep_str = "-13".to_string();
        b.maneuver_state_str = "OVERLOAD".to_string();
        b.warn_configuration = true;
        b.aoa_ratio = 1.05;
        b.speed_bar_speed_ratio = 0.83;
        b.speed_bar_stall_ratio = 0.31;
        b.speed_bar_unit_mach_limit_ratio = 0.9;
        b.speed_bar_aileron_lock_ratio = 0.72;
        b.speed_bar_rudder_lock_ratio = 0.66;

        let h = b.build();
        assert_eq!(h.ias, 412.5);
        assert_eq!(h.mach, 0.82);
        assert_eq!(h.altitude, 5300.0);
        assert_eq!(h.radio_altitude, 245.7);
        assert_eq!(h.vertical_speed, -13.2);
        assert_eq!(h.heading, 359.9);
        assert_eq!(h.pitch, -12.25);
        assert_eq!(h.roll, 60.0);
        assert_eq!(h.slip, 0.5);
        assert_eq!(h.aoa, 18.3);
        assert!(h.pitch_valid);
        assert_eq!(h.throttle, 110);
        assert_eq!(h.flaps, 100.0);
        assert_eq!(h.gear, 55.0);
        assert_eq!(h.airbrake, 20.0);
        assert_eq!(h.flap_allow_angle, 25.0);
        assert_eq!(h.energy_m, 1520.4);
        assert_eq!(h.g_load, 7.5);
        assert_eq!(h.turn_rate, 22.4);
        assert_eq!(h.maneuver_index, 0.97);
        assert!(h.is_mach_mode);
        assert!(h.is_gear_down);
        assert!(h.is_flaps_down);
        assert!(h.is_airbrake_active);
        assert!(h.warn_vne);
        assert!(h.warn_stall);
        assert!(h.warn_gear);
        assert!(h.warn_altitude);
        assert_eq!(h.aoa_color, [255, 64, 64, 255]);
        assert_eq!(h.aoa_bar_color, [255, 192, 0, 128]);
        assert_eq!(h.throttle_color, [64, 255, 128, 200]);
        assert_eq!(h.map_grid, "C4");
        assert_eq!(h.time_str, "12:34");
        assert_eq!(h.speed_str, "413");
        assert_eq!(h.alt_str, "5300");
        assert_eq!(h.aoa_str, "18.3");
        assert_eq!(h.energy_str, "1520");
        assert_eq!(h.mechanization_str, "F100");
        assert_eq!(h.flaps_wing_str, "W 50");
        assert_eq!(h.airbrake_str, "BRK");
        assert_eq!(h.gear_str, "GEA");
        assert_eq!(h.sep_str, "-13");
        assert_eq!(h.maneuver_state_str, "OVERLOAD");
        assert_eq!(h.aoa_ratio, 1.05);
        assert!(h.warn_configuration);
        assert_eq!(h.speed_bar_speed_ratio, 0.83);
        assert_eq!(h.speed_bar_stall_ratio, 0.31);
        assert_eq!(h.speed_bar_unit_mach_limit_ratio, 0.9);
        assert_eq!(h.speed_bar_aileron_lock_ratio, 0.72);
        assert_eq!(h.speed_bar_rudder_lock_ratio, 0.66);
    }

    /// Java `build()` 非消费: 同一 Builder 重复 build 得到相等 (但独立) 的实例。
    #[test]
    fn builder_is_reusable() {
        let mut b = Builder::default();
        b.ias = 250.0;
        b.map_grid = "A1".to_string();
        let h1 = b.build();
        let h2 = b.build();
        assert_eq!(h1, h2);
        // Java 每次返回 new HUDData (独立实例); Rust 值语义下以变异隔离证明非别名
        let mut h1 = h1;
        h1.ias = 999.0;
        assert_ne!(h1.ias, h2.ias);
        assert_eq!(h2.ias, 250.0);
    }
}
