package ui.overlay.model;

import java.awt.Color;

/**
 * Immutable value object containing all necessary data for one frame of HUD
 * rendering.
 * Generated by HUDCalculator.
 */
public class HUDData {

    // Flight Dynamics
    public final double ias; // Indicated Airspeed (km/h)
    public final double mach; // Mach number
    public final double altitude; // Barometric altitude (m)
    public final double radioAltitude; // Radio altitude (m)
    public final double verticalSpeed; // SEP (m/s)
    public final double heading; // Heading (degrees, 0-360)
    public final double pitch; // Pitch (degrees)
    public final double roll; // Roll (degrees)
    public final double slip; // Side slip (deg or relative)
    public final double aoa; // Angle of Attack

    // System State
    public final int throttle; // 0-110%
    public final double flaps; // 0-100%
    public final double gear; // 0-100%
    public final double airbrake; // 0-100%

    // Calculated/Derived Metrics
    public final double energyM; // Energy/Mass
    public final double gLoad; // Ny
    public final double turnRate; // Degrees/sec
    public final double maneuverIndex; // 0.0 - 1.0 (Energy Maneuverability)
    public final boolean isMachMode;
    public final boolean isGearDown;
    public final boolean isFlapsDown;
    public final boolean isAirbrakeActive;

    // Warnings & Limits
    public final boolean warnVne; // Velocity Not Exceed
    public final boolean warnStall; // AoA Limit
    public final boolean warnGear; // Gear speed warning
    public final boolean warnAltitude; // Ground proximity
    public final Color aoaColor; // Color for AoA indicator
    public final Color throttleColor; // Color for Throttle

    // Context Info
    public final String mapGrid; // e.g. "C4"
    public final String timeStr; // Mission time or Fuel time

    // Formatting Helpers (Optional, can be computed by components if raw data is
    // sufficient)
    public final String speedStr;
    public final String altStr;

    public HUDData(Builder builder) {
        this.ias = builder.ias;
        this.mach = builder.mach;
        this.altitude = builder.altitude;
        this.radioAltitude = builder.radioAltitude;
        this.verticalSpeed = builder.verticalSpeed;
        this.heading = builder.heading;
        this.pitch = builder.pitch;
        this.roll = builder.roll;
        this.slip = builder.slip;
        this.aoa = builder.aoa;
        this.throttle = builder.throttle;
        this.flaps = builder.flaps;
        this.gear = builder.gear;
        this.airbrake = builder.airbrake;
        this.energyM = builder.energyM;
        this.gLoad = builder.gLoad;
        this.turnRate = builder.turnRate;
        this.maneuverIndex = builder.maneuverIndex;
        this.isMachMode = builder.isMachMode;
        this.isGearDown = builder.isGearDown;
        this.isFlapsDown = builder.isFlapsDown;
        this.isAirbrakeActive = builder.isAirbrakeActive;
        this.warnVne = builder.warnVne;
        this.warnStall = builder.warnStall;
        this.warnGear = builder.warnGear;
        this.warnAltitude = builder.warnAltitude;
        this.aoaColor = builder.aoaColor;
        this.throttleColor = builder.throttleColor;
        this.mapGrid = builder.mapGrid;
        this.timeStr = builder.timeStr;
        this.speedStr = builder.speedStr;
        this.altStr = builder.altStr;
    }

    public static class Builder {
        // Defaults
        public double ias;
        public double mach;
        public double altitude;
        public double radioAltitude;
        public double verticalSpeed;
        public double heading;
        public double pitch;
        public double roll;
        public double slip;
        public double aoa;
        public int throttle;
        public double flaps;
        public double gear;
        public double airbrake;
        public double energyM;
        public double gLoad;
        public double turnRate;
        public double maneuverIndex;
        public boolean isMachMode;
        public boolean isGearDown;
        public boolean isFlapsDown;
        public boolean isAirbrakeActive;
        public boolean warnVne;
        public boolean warnStall;
        public boolean warnGear;
        public boolean warnAltitude;
        public Color aoaColor = Color.GREEN;
        public Color throttleColor = Color.GREEN;
        public String mapGrid = "";
        public String timeStr = "";
        public String speedStr = "";
        public String altStr = "";

        public HUDData build() {
            return new HUDData(this);
        }
    }
}
